name: CI

on:
  push:


jobs:
  Web:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Flutter version from pubspec
        run: |
          set -e
          FLUTTER_VERSION=$(cat pubspec.yaml | grep 'flutter:' | head -n 1 | awk '{ print $2 }' | tr -d '"' | cut -d "=" -f 2)
          echo "FLUTTER_VERSION=${FLUTTER_VERSION}" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - run: flutter pub get --suppress-analytics
        name: Get Flutter Deps

      - name: Build
        run: ./scripts/build_web.sh

      - name: Save HTML
        uses: actions/upload-artifact@v3
        with:
          name: Web
          path: ./dist

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
